# Generated by Django 4.2 on 2023-04-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Roll_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=100)),
                ('Mark', models.CharField(max_length=100)),
                ('Collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.collage')),
            ],
        ),
    ]
