# Generated by Django 4.2 on 2023-04-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collage',
            new_name='Student_Details',
        ),
    ]
