# Generated by Django 4.2 on 2023-04-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_collage_student_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marklist',
            old_name='Collage',
            new_name='Student_Details',
        ),
    ]
